### ISSUE TITLE
[Epic] Wallet Service v1

### ISSUE THREAD

**Issue by obiyankenobi** [HathorNetwork/hathor-wallet-service-old#5]
# Introduction

The hathor-wallet-service will be used as a backend for all official Hathor's wallets.

This service is highly inspired by the [Bitcore Wallet Service](https://github.com/bitpay/bitcore-wallet-service).

# Motivation

The idea behind this service is to have a fully indexed Hathor blockchain in real-time on a centralized database so we don't have to seek the full-node to calculate his balances and to query his utxos it every time a user wants to use his wallet, thereby making the app a lot faster for large wallets and reducing the load on the full nodes.

# Acceptance criteria

Aside from faster load times, the apps that are using this service as their backends should have all features working exactly as they were working when connected directly on the fullnode.

We should have control over exactly what percentage of our user base should be using this service and these percentages should be configured for each platform individually 

## Q3 Week 7: Aug 16th - Aug 20th
- [x] https://github.com/HathorNetwork/hathor-wallet-lib/issues/215 - @pedroferreira1 
- [x] https://github.com/HathorNetwork/hathor-wallet-mobile/issues/101 - @pedroferreira1
- [x] https://github.com/HathorNetwork/hathor-wallet-mobile/issues/114 - @andreabadesso 
- [x] https://github.com/HathorNetwork/hathor-wallet-mobile/issues/113 - @andreabadesso 
- [ ] https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/8 - @andreabadesso

## Q3 Week 6: Aug 9th - Aug 13th
- [Partial] https://github.com/HathorNetwork/hathor-wallet-mobile/issues/114 - @andreabadesso 
    - Made some progress this week, still needs more work to complete
- [Fail] https://github.com/HathorNetwork/hathor-wallet-mobile/issues/113 - @andreabadesso 
    - No progress this week 
- [Fail] https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/8 - @andreabadesso
    - No progress this week
- [Partial] https://github.com/HathorNetwork/hathor-wallet-lib/issues/215 - @pedroferreira1 
- [Partial] https://github.com/HathorNetwork/hathor-wallet-mobile/issues/101 - @pedroferreira1

### In Review (from previous weeks)

- [Done] https://github.com/HathorNetwork/hathor-wallet-service/pull/112 - @andreabadesso 
- [Done] https://github.com/HathorNetwork/hathor-wallet-service/pull/82 - @andreabadesso 
- [Partial] https://github.com/HathorNetwork/hathor-wallet-service/pull/117 - @andreabadesso 
    - There is an ongoing discussion about how to wrap the method with a db transaction. I refactored it to the latest @msbrogli suggestion and now the issue is pending a re-review
- [Partial] https://github.com/HathorNetwork/hathor-wallet-service/pull/116 - @andreabadesso 
    - This PR has 3 approves, but they're still one change that @msbrogli asked for. The change is done, pending a re-review on that specific point: https://github.com/HathorNetwork/hathor-wallet-service/pull/117#discussion_r689709369

## Q3 Week 5: Aug 2nd - Aug 6th
- [Done] https://github.com/HathorNetwork/hathor-wallet-lib/issues/197 - @pedroferreira1
- [Partial] https://github.com/HathorNetwork/hathor-wallet-lib/issues/215 - @pedroferreira1 
- [Partial] https://github.com/HathorNetwork/hathor-wallet-mobile/issues/101 - @pedroferreira1
- [Done] https://github.com/HathorNetwork/hathor-wallet-service/issues/75 - @andreabadesso 
- [In Review] https://github.com/HathorNetwork/hathor-wallet-service/pull/116 - @andreabadesso 
    - This issue replaced #89 with a different approach. It is ready to review
- [Partial] https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/8 - @andreabadesso
    - Didn't work on this issue this week, still pending some tests, but implementation is ready
- [In Review] https://github.com/HathorNetwork/hathor-wallet-service/issues/114 - @andreabadesso 
    - Done and currently in review
- [Fail] https://github.com/HathorNetwork/hathor-wallet-service/issues/101 - @andreabadesso
    - No progress yet
- [Fail] https://github.com/HathorNetwork/hathor-wallet-mobile/issues/113 - @andreabadesso 
    - No progress yet

### Unplanned issues
- [Done] https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/18 - @andreabadesso 

## Q3 Week 4: Jul 26th - Jul 30th
- [Partial] https://github.com/HathorNetwork/hathor-wallet-lib/issues/197 - @pedroferreira1
- [Partial] https://github.com/HathorNetwork/hathor-wallet-lib/issues/215 - @pedroferreira1 
- [Partial] https://github.com/HathorNetwork/hathor-wallet-mobile/issues/101 - @pedroferreira1
- [Fail] https://github.com/HathorNetwork/hathor-wallet/issues/208 - @pedroferreira1
- [Partial] https://github.com/HathorNetwork/hathor-wallet-service/pull/89 - @andreabadesso
    - I spent very little time on this issue, still needs ~4h work to finish it
- [Partial] https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/8 - @andreabadesso 
    - Also spent very little time on it, needs to improve tests to open the PR
- [Partial] https://github.com/HathorNetwork/hathor-wallet-service/issues/101 - @andreabadesso 
    - Had some progress on it, identified some issues with the loadWallet, still some work to be done
- [In Review] https://github.com/HathorNetwork/hathor-wallet-service/issues/110 - @andreabadesso
    - Done and currently in review
- [Done] https://github.com/HathorNetwork/hathor-wallet-service/pull/107 - @andreabadesso 
    - Done in the beginning of the week
- [Fail] chore: test with large wallets (20k+ txs) - @andreabadesso
    - Didn't work on this issue 
- [Moved to parking lot] https://github.com/HathorNetwork/hathor-wallet-service/issues/84 - @r4mmer 

## Q3 Week 3: Jul 19th - Jul 23rd
- [Partial] https://github.com/HathorNetwork/hathor-wallet-lib/issues/197 - @pedroferreira1 
- [Partial] https://github.com/HathorNetwork/hathor-wallet-lib/issues/215 - @pedroferreira1 
- [Partial] https://github.com/HathorNetwork/hathor-wallet-mobile/issues/101 - @pedroferreira1
- [Fail] https://github.com/HathorNetwork/hathor-wallet/issues/208 - @pedroferreira1
- [Partial] https://github.com/HathorNetwork/hathor-wallet-service/pull/89 - @andreabadesso 
    - Had some progress on this PR, I have a working proof of concept developed but decided on a new, simpler mechanism for voiding transactions that is yet to be discussed and developed.
- [Partial] https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/8 - @andreabadesso
    - Also had some progress last week, I am sending the voided transactions as they are received from the WebSocket but depending on #89, there will be some changes necessary on the daemon as well
- [Partial] https://github.com/HathorNetwork/hathor-wallet-service/pull/107 - @andreabadesso
    - This is already approved by @msbrogli and @pedroferreira1 but is still pending an answer from @msbrogli so it can be merged
- [Partial] https://github.com/HathorNetwork/hathor-wallet-service/issues/101 - @andreabadesso 
    - Listed some queries that need to be worked on and opened a PR (#108) that should've been part of this issue but had to be merged so the daemon wouldn't stop every time this function was called. 
- [Fail] chore: test with large wallets (20k+ txs) - @andreabadesso
    - No progress
- [Fail] Discuss with @msbrogli the feasibility of using the fullnode database directly instead of the current sync implementation
    - Did not discuss
- [Partial] https://github.com/HathorNetwork/hathor-wallet-service/issues/84 - @r4mmer 
    - Implementation is done and tested, but there are still some pending discussions about timeout configuration and potential optimizations to the auth implementation
- [Partial] https://github.com/HathorNetwork/hathor-wallet-service/issues/80 - @luislhl 
    - @luislhl finished the design with suggestions for each point, those suggestions are being discussed on the PR  

### Unplanned issues:
- [Done] https://github.com/HathorNetwork/hathor-wallet-service/pull/108 - @andreabadesso 
- [Done] https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/17 - @andreabadesso 
- [Done] https://github.com/HathorNetwork/hathor-wallet-lib/pull/216 - @andreabadesso 

## Q3 Week 2: Jul 12th - Jul 16th
- [Partial] https://github.com/HathorNetwork/hathor-wallet-lib/issues/197 - @pedroferreira1 
- [Partial] https://github.com/HathorNetwork/hathor-wallet-mobile/issues/101 - @pedroferreira1
- [Partial] https://github.com/HathorNetwork/hathor-wallet/issues/208 - @pedroferreira1
- [In Review] https://github.com/HathorNetwork/hathor-wallet-service/pull/82 - @andreabadesso
  - The `txProposalSend` API was refactored entirely. This is currently deployed on a Lambda staging environment and was already tested by @pedroferreira1
- [In Review] https://github.com/HathorNetwork/hathor-wallet-service/issues/75 - @andreabadesso 
- [Partial] https://github.com/HathorNetwork/hathor-wallet-service/issues/80 - @luislhl 
  - Status on Operational Excellence Epic: https://github.com/HathorNetwork/ops-tools/issues/36
- [Fail] https://github.com/HathorNetwork/hathor-wallet-service/pull/89 - @andreabadesso 
  - Started the week working on this but had to stop to work on the unplanned issues and the necessary changes for the token actions API
- [Fail] https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/8 - @andreabadesso
  - Same as above 
- [Done] https://github.com/HathorNetwork/hathor-wallet-service/pull/94 - @r4mmer
- [In Review] https://github.com/HathorNetwork/hathor-wallet-service/issues/84 - @r4mmer 

### Unplanned issues:

- [Done] https://github.com/HathorNetwork/hathor-wallet-service/pull/104 - @andreabadesso 
- [Done] https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/14 - @andreabadesso 
- [Done] https://github.com/HathorNetwork/hathor-wallet-service/pull/90 - @andreabadesso 
- [Done] https://github.com/HathorNetwork/hathor-wallet-service/pull/93 - @andreabadesso 
- [Done] https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/15 - @andreabadesso 
- [Done] https://github.com/HathorNetwork/hathor-wallet-service/pull/102 - @andreabadesso 
- [Done] https://github.com/HathorNetwork/ops-tools/pull/57 - @luislhl 
- [Done] https://github.com/HathorNetwork/ops-tools/pull/58 - @luislhl 
- [Done] https://github.com/HathorNetwork/ops-tools/pull/60 - @luislhl 
- [Done] https://github.com/HathorNetwork/ops-tools/pull/59 - @luislhl 

## Q3 Week 1: Jul 5th - Jul 9th
- [Partial] https://github.com/HathorNetwork/hathor-wallet-lib/issues/197 - @pedroferreira1 
- [Fail] https://github.com/HathorNetwork/hathor-wallet-mobile/issues/101 - @pedroferreira1
- [Fail] https://github.com/HathorNetwork/hathor-wallet/issues/208 - @pedroferreira1 
- [Done] Debug wallet-service high costs with @luislhl - @andreabadesso
- [Partial] https://github.com/HathorNetwork/hathor-wallet-service/pull/82 - @andreabadesso
- [Partial] https://github.com/HathorNetwork/hathor-wallet-service/issues/75 - @andreabadesso  
- [Partial] https://github.com/HathorNetwork/hathor-wallet-service/issues/80 - @andreabadesso 
- [Fail] https://github.com/HathorNetwork/hathor-wallet-service/pull/89 - @andreabadesso 
- [Fail] https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/8 - @andreabadesso
- [Partial] https://github.com/HathorNetwork/hathor-wallet-service/pull/94 - @r4mmer
- [Partial] https://github.com/HathorNetwork/hathor-wallet-service/issues/84 - @r4mmer 

## Q2 Week 13: Jun 28th-Jul 02nd
- [Done] Deploy a new wallet-service and daemon instance to sync with the `mainnet` - @luislhl  
- [Fail] [Test the re-org strategy with more simulation strategies on the wallet service](https://github.com/orgs/HathorNetwork/projects/3#card-62647664) - @andreabadesso
- [Done] https://github.com/HathorNetwork/hathor-wallet-service/pull/83 - @andreabadesso 
- [Partial] https://github.com/HathorNetwork/hathor-wallet-service/pull/82 - @andreabadesso
- [Partial] https://github.com/HathorNetwork/hathor-wallet-service/issues/75 - @andreabadesso  
- [Done] https://github.com/HathorNetwork/hathor-wallet-service/pull/74 - @andreabadesso 
- [Partial] https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/8 - @andreabadesso
- [Partial] https://github.com/HathorNetwork/hathor-wallet-lib/issues/197 - @pedroferreira1 
- [Fail] https://github.com/HathorNetwork/hathor-wallet-mobile/issues/101 - @pedroferreira1
- [Done] Mempool reviews for [Full-Node api](https://github.com/HathorNetwork/sec-hathor-core/issues/68) and [Daemon](https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/11) - @r4mmer 
- [Done] https://github.com/HathorNetwork/hathor-wallet-service/pull/81 - @r4mmer
- [Done] https://github.com/HathorNetwork/hathor-wallet-service/pull/69 - @r4mmer 

## Q2 Week 12: Jun 21th-Jun 25th
- [Done] [Send transactions before sending the block on daemon](https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/12) - @andreabadesso 
- [Partial] [Test the wallet service re-org strategy](https://github.com/orgs/HathorNetwork/projects/3#card-62647664) - @andreabadesso 
- [Partial] [New design/PoC Token Actions & implementation](https://github.com/HathorNetwork/hathor-wallet-service/issues/75) - @andreabadesso 
- [Fail] [Daemon: Sync voided transactions](https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/8) - @andreabadesso 
- [Partial] [design: OPS - Rate Limit, Alerts, Monitoring, QA, Deployment Steps](https://github.com/HathorNetwork/hathor-wallet-service/pull/78) - @andreabadesso 
- [Fail] [Add support for new token actions in the wallet lib](https://github.com/HathorNetwork/hathor-wallet-lib/issues/197) - @pedroferreira1 
- [Fail] [Add support in wallet mobile for wallet service](https://github.com/HathorNetwork/hathor-wallet-mobile/issues/101) - @pedroferreira1 
- [In Review] Mempool reviews for [Full-Node api](https://github.com/HathorNetwork/sec-hathor-core/issues/68) and [Daemon](https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/11) - @r4mmer 
- [In Review] Wallet Service: Finish out-of-order and reviews - @r4mmer
- [Blocked] Wallet Service: Test Authorization with new hathor-wallet-lib version - @r4mmer 

## Q2 Week 11: Jun 14th-Jun 18th

- [Partial] [Test the wallet service re-org strategy](https://github.com/orgs/HathorNetwork/projects/3#card-62647664) - @andreabadesso 
- [Partial] [New design/PoC Token Actions & implementation](https://github.com/HathorNetwork/hathor-wallet-service/issues/75) - @andreabadesso 
- [Fail] [Daemon: Sync voided transactions](https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/8) - @andreabadesso 
- [Partial] [design: OPS - Rate Limit, Alerts, Monitoring, QA, Deployment Steps](https://github.com/HathorNetwork/hathor-wallet-service/pull/78) - @andreabadesso 
- [Done] - Deploy the wallet-service and the daemon to the staging server with the latest handle-reorg merges - @andreabadesso 
- [Done] - [Improve the serverless deployment by creating the SQS queue automatically](https://github.com/HathorNetwork/hathor-wallet-service/pull/78) - @andreabadesso 
- [Done] [Wallet Service Daemon: sync mempool](https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/11) - @r4mmer 
- [Done] [Full-Node: mempool api](https://github.com/HathorNetwork/sec-hathor-core/issues/68) - @r4mmer 
- [Partial] Wallet Service: handle out-of-order mempool TXs - @r4mmer 
- [Done] Finish wallet rollout design decision (https://github.com/HathorNetwork/internal-issues/issues/11) - @pedroferreira1 
- [Fail] Add support for new token actions in the wallet lib - @pedroferreira1 
- [Fail] Add support in wallet mobile for wallet service (https://github.com/HathorNetwork/hathor-wallet-mobile/issues/101) - @pedroferreira1 

## Q2 Week 10: Jun 7th-Jun 11th

- [Done] Wallet Service: Handle voided tx design and implementation - @andreabadesso 
- [Fail] Wallet Service: Test the wallet service re-org strategy - @andreabadesso 
- [Partial] Wallet Service: New design/PoC Token Actions & implementation - @andreabadesso 
- [Fail] Wallet Service: handle out-of-order mempool TXs - @r4mmer 
- [Partial] Full-Node: mempool api - @r4mmer 
- [Partial] Daemon: sync mempool - @r4mmer 

## Q2 Week 9: May 31st-Jun 4th

- [Partial] Wallet Service: Handle voided tx design and implementation
- [Partial] Wallet Service: Test the wallet service re-org strategy
- [Fail] Wallet Service: New design/PoC Token Actions & implementation

## Design Issues

- [General Design](https://github.com/HathorNetwork/hathor-wallet-service/issues/10) (replaces https://github.com/HathorNetwork/hathor-wallet-service/issues/1)
- [Mempool Sync](https://github.com/HathorNetwork/hathor-wallet-service/issues/73)
- [Wallet Service Authentication](https://github.com/HathorNetwork/hathor-wallet-service/issues/66)
- [Possible solutions for handling reorgs and balance recalculation](https://github.com/HathorNetwork/hathor-wallet-service/issues/60)
- [Update wallets in real-time (guide-level explanation)](https://github.com/HathorNetwork/hathor-wallet-service/issues/50)
- [Sync with the full-node](https://github.com/HathorNetwork/hathor-wallet-service/issues/35)

## Pending issues to fulfill the design:
- [x] [Return the full derivation path for inputs on POST /txProposal](https://github.com/HathorNetwork/hathor-wallet-service/issues/19)
- [x] [TxProcessor should be idempotent](https://github.com/HathorNetwork/hathor-wallet-service/issues/18)
- [ ] [POST /wallet needs a lock system to prevent errors with two requests arriving simultaneously](https://github.com/HathorNetwork/hathor-wallet-service/issues/17)
- [ ] [TxHistory should receive AfterAddress and Count instead of Skip and Count](https://github.com/HathorNetwork/hathor-wallet-service/issues/16)
- [x] [feat: handle reorg](https://github.com/HathorNetwork/hathor-wallet-service/pull/71)

## Pending tasks breakdown
- [x] [feat: send transactions in topological order](https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/9)
- [x] [feat: ignoring genesis transactions](https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/5)
- [x] [refactor: using the transactions table to handle blocks](https://github.com/HathorNetwork/hathor-wallet-service/pull/76)
- [x] feat: handle timelock balance
- [x] feat: tx-proposal code (to send txs)
- [x] feat: handle authority outputs
- [X] feat: tx-proposal token actions Design: https://github.com/HathorNetwork/hathor-wallet-service/issues/14 PR: https://github.com/HathorNetwork/hathor-wallet-service/pull/61
- [ ] refactor: database ORM (like sequelize) - [estimated work: 24h]
- [x] refactor: database transaction/rollback support and error handling - This will come "free" from the ORM if we decide to use SequelizeJS - [estimated: 8h]
- [x] design: Wallet Sync and Voided Txs Strategy - [estimated work: 40h]
    - [x] Implementation: https://github.com/HathorNetwork/hathor-wallet-service/pull/72 (Currently in progress by @r4mmer)
- [x] Develop a daemon that will listen for full node WebSocket messages and trigger block sync
    - [x] Method that will sync blocks from a height range
    - [x] Reorg strategy
    - [x] Balance recalculation on reorgs - 5h https://github.com/HathorNetwork/hathor-wallet-service/issues/60 https://github.com/HathorNetwork/hathor-wallet-service/issues/64 (Currently in review)
        - [x] [Invoke the re-org from the daemon on the reorg state](https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/7) - 2h
        - [ ] Manually test the `address_balance` recalculation on multiple tokenIds - 2h
        - [x] Increase coverage on the wallet-service - 1h
        - [ ] Automated tests using the hathor-core simulator - 8h 
    - [x] Improve daemon tests - 4h
- [x] https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/11
- [x] feat: handle voided txs (Currently in progress by @andreabadesso)
    - [x] New route to receive UPDATE_TX events - 2h
    - [ ] The daemon should send the UPDATE_TX events - 3h
- [x] refactor: return correct status codes for errors and sucesses - [estimated work: 6h]
- [ ] docs: open API docs - [estimated work: 4h]
- [x] [feat: [Needs Design] wallet authentication](https://github.com/HathorNetwork/hathor-wallet-service/pull/69) - [estimated work includ. design: 40h] (Currently in progress by @r4mmer)
- [ ] chore: test with large wallets (20k+ txs) - [estimated work: 6h]
- [x] refactor: optimize database (add indexes and use binary columns) - [estimated work: 16h]
- [x] design: OPS - Rate Limit, Alerts, Monitoring, QA, Deployment Steps - [estimated work: 16h]
- [x] design: use the wallet service in the wallets - [estimated work: 40h for the wallets desktop and mobile]
    - [x] [Finish wallet rollout low level design](https://github.com/HathorNetwork/internal-issues/issues/11)
    - [x] Add support for new token actions in the wallet lib
    - [x] [Add support in wallet mobile for wallet service](https://github.com/HathorNetwork/hathor-wallet-mobile/issues/101)
    - [x] Add support for all wallets with rollout logic

### Summary

Total: 336h / 42 days / 8.4 weeks, i.e., end of Q1/2021.

**Comment by andreabadesso** [comment]
Here is the estimated work for the breakdown tasks:

handle timelock balance
tx-proposal code (to send txs)
handle authority outputs
[tx-proposal code (token actions)](https://github.com/HathorNetwork/hathor-wallet-service/issues/14) - [estimated work: 40h]
handle voided txs - [estimated work: 12h]
database transaction/rollback support and error handling - This will come "free" from the ORM if we decide to use SequelizeJS
database ORM (like sequelize) - [estimated work: 24h]
optimize database (add indexes and use binary columns) - [estimated work: 16h]
open API docs - [estimated work: 8h]
[wallet sync strategy (websocket?)](https://github.com/HathorNetwork/hathor-wallet-service/issues/8) - [estimated work: 40h]
[Needs Design] wallet authentication - [estimated work includ. design: 40h]
test with large wallets (20k+ txs) - [estimated work: 6h]

**Comment by andreabadesso** [comment]
# Q3 Planning

## Q2 spill-overs

- [ ] [feat: TxHistory should receive AfterAddress and Count instead of Skip and Count](https://github.com/HathorNetwork/hathor-wallet-service/issues/16) - 8h
- [ ] [feat: POST /wallet needs a lock system to prevent two requests arriving simultaneously](https://github.com/HathorNetwork/hathor-wallet-service/issues/17) - 12h
- [ ] [refactor: Database ORM (like sequelize)](https://github.com/HathorNetwork/hathor-wallet-service/issues/98) - 24h
- [x] [refactor: Database transaction/rollback support and error handling ](https://github.com/HathorNetwork/hathor-wallet-service/issues/99) - 8h
- [ ] chore: Manually test the address_balance recalculation on multiple tokenIds - 4h
- [ ] [chore: Automated tests using the hathor-core simulator](https://github.com/HathorNetwork/hathor-wallet-service/issues/100) - 8h
- [x] [feat: Handle voided transactions on wallet-service daemon](https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/8) - 8h
- [x] [feat: Handle voided transactions on wallet-service](https://github.com/HathorNetwork/hathor-wallet-service/pull/89) - 8h
- [x] [refactor: Optimize database (add indexes and use binary columns)](https://github.com/HathorNetwork/hathor-wallet-service/issues/101) - 12h
- [x] [design: OPS - Rate Limit, Alerts, Monitoring, QA, Deployment Steps](https://github.com/HathorNetwork/hathor-wallet-service/issues/80) - 8h
- [ ] [feat: Authorization for the websocket connection](https://github.com/HathorNetwork/hathor-wallet-service/issues/84) - 12h

Total: 112h (~3 weeks, includ. current)

## Q3

- [ ] chore: database healthcheck to be able to check if state is consistent with the fullnode - 24h
- [ ] feat: Multisig support on txProposalCreate - 32h
- [ ] feat: Nano Contracts support - ?h
- [ ] feat: Atomic Swap support - ?h

## Q3 - Data Service
